export enum TELE_BOX_MANAGER_EVENT {
    Focused = "focused",
    Blurred = "blurred",
    Created = "created",
    Removed = "removed",
    State = "state",
    Maximized = "maximized",
    Minimized = "minimized",
    Move = "move",
    Resize = "resize",
    IntrinsicMove = "intrinsic_move",
    IntrinsicResize = "intrinsic_resize",
    VisualResize = "visual_resize",
    ZIndex = "z_index",
    PrefersColorScheme = "prefers_color_scheme",
    DarkMode = "dark_mode",
}
